### PR TITLE
Add solder jumper package and device

### PR DESCRIPTION
**Pull request by rnestler**
image

### CODE REVIEW

**Review by dbrgn — APPROVED** [review]
I'm still not sure about the polarized silkscreen, it looks a bit strange on a jumper. But let's merge it for now!

**Comment by rnestler** [comment]
> I'm still not sure about the polarized silkscreen, it looks a bit strange on a jumper. But let's merge it for now!

Well if you break it up and want to measure, it is helpful to know which pin is which.

**Comment by dbrgn** [comment]
Btw, it was not *that* easy to solder. Adding a dab of solder paste across it before reflowing didn't work, the pads were not connected after reflowing. With a soldering iron it worked out after adding a lot of solder, but you could see the surface tension trying to pull the bridge apart.

**Comment by rnestler** [comment]
> Btw, it was not that easy to solder. Adding a dab of solder paste across it before reflowing didn't work, the pads were not connected after reflowing. With a soldering iron it worked out after adding a lot of solder, but you could see the surface tension trying to pull the bridge apart.

Yes, I was thinking that it may be to far apart, but others convinced me that less space between the pads would be too hard to break up the connection :wink:. For reflow we'd probably need to add a 0-ohm resistor.

**Pull request merged**
